---
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "weather_app"
    static_configs:
      - targets: ["weather-app:5000"]

  - job_name: "grafana"
    metrics_path: /metrics
    static_configs:
      - targets: ["grafana:3000"]

  - job_name: "loki"
    metrics_path: /metrics
    static_configs:
      - targets: ["loki:3100"]

  - job_name: "promtail"
    metrics_path: /metrics
    static_configs:
      - targets: ["promtail:9080"]

  - job_name: "statporter"
    metrics_path: /metrics
    static_configs:
      - targets: ["statporter:9800"]
