- name: Install MySQL server
  ansible.builtin.yum:
    name: mariadb-server
    state: present

- name: Start and enable MySQL
  ansible.builtin.service:
    name: mariadb
    state: started
    enabled: yes
