---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/weather-app/docker-final"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/weather-app/docker-src"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/weather-app/docker-final/statporter"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/weather-app/demo-container"
    schedule:
      interval: "weekly"
