version: "3.8"
services:
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  wazuh.manager:
    image: wazuh/wazuh-manager:4.7.2
    ports:
      - "1514:1514/udp" # Agent communication
      - "1515:1515" # Registration
    volumes:
      - wazuh_manager_data:/var/ossec/data

  wazuh.indexer:
    image: wazuh/wazuh-indexer:4.7.2
    environment:
      - "OPENSEARCH_INITIAL_ADMIN_PASSWORD=admin"
    ports:
      - "9200:9200"
    volumes:
      - wazuh_indexer_data:/usr/share/opensearch/data
  wazuh.dashboard:
    image: wazuh/wazuh-dashboard:4.7.2
    depends_on:
      - wazuh.indexer
    ports:
      - "5601:5601"
    environment:
      - "INDEXER_USERNAME=admin"
      - "INDEXER_PASSWORD=admin"
      - "INDEXER_HOST=wazuh.indexer"

volumes:
  grafana-data:
  wazuh_manager_data:
  wazuh_indexer_data:
