version: "3.8"
services:
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  terraform:
    image: hashicorp/terraform:latest
    volumes:
      - ./controlTower-terraform:/workspace
    command: ["tail", "-f", "/dev/null"]

  ansible:
    image: williamyeh/ansible:alpine3
    volumes:
      - ./controlTower-ansible:/workspace
    command: ["tail", "-f", "/dev/null"]

volumes:
  grafana-data:
