---
global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["localhost:9093"]

rule_files: []

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets:
          - "localhost:9090"
        labels:
          node: "metric"

  - job_name: "node_exporters"
    static_configs:
      - targets:
          - "localhost:9100"
          - "veritas.dreadnought.lab:9100"
          - "highcommand.dreadnought.lab:9100"
          - "anorlondo:9100"
