version: "3.8"

services:
  reverse-proxy:
    image: nginx:alpine
    container_name: reverse-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - weather-app
      - grafana
      - prometheus
      # - kibana  # for later
    networks:
      - monitoring
    labels:
      - "logging=true"

  weather-app:
    image: burningstar4/weather-app:latest
    container_name: weather-app
    expose:
      - "5000"
    labels:
      - "app=weather"
      - "logging=true"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    expose:
      - "9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    labels:
      - "logging=true"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    expose:
      - "3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/dashboards:/etc/grafana/dashboards
    depends_on:
      - prometheus
      - loki
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s/grafana
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    labels:
      - "logging=true"
    networks:
      - monitoring

  loki:
    image: grafana/loki:latest
    container_name: loki
    expose:
      - "3100"
    volumes:
      - ./loki/loki-config.yaml:/etc/loki/loki-config.yaml
      - loki-data:/loki
    command: -config.file=/etc/loki/loki-config.yaml
    labels:
      - "logging=true"
    networks:
      - monitoring

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - ./promtail/promtail-config.yaml:/etc/promtail/promtail.yaml
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /tmp:/tmp
    command: -config.file=/etc/promtail/promtail.yaml
    depends_on:
      - loki
    labels:
      - "logging=true"
    networks:
      - monitoring

  statporter:
    image: burningstar4/statporter:latest
    container_name: statporter
    restart: unless-stopped
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    expose:
      - "9800"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "logging=true"
    networks:
      - monitoring

volumes:
  grafana-data:
  loki-data:

networks:
  monitoring:
    driver: bridge
