---
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: system
          __path__: /var/log/*.log

  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock

    pipeline_stages:
      - docker: {}
      - json:
          expressions:
            asctime:
            levelname:
            name:
            message:
            pathname:
            lineno:
            event:
            request_id:
            method:
            path:
            remote_addr:
            status:

    relabel_configs:
      - source_labels: [__meta_docker_container_log_stream]
        target_label: stream

      - source_labels: [__meta_docker_container_name]
        regex: "/?(.*)"
        target_label: container

      - source_labels: [__meta_docker_container_id]
        target_label: container_id

      - source_labels: [__meta_docker_container_image]
        target_label: image

      - source_labels: [__meta_docker_container_name]
        target_label: job

      - source_labels: [__meta_docker_container_label_logging]
        regex: "true"
        action: keep
