---
name: Docker Build and Push - Statporter

on:
  push:
    branches:
      - master
    paths:
      - "weather-app/docker-final/statporter/**"

jobs:
  build-statporter:
    name: Build and Push Statporter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push statporter
        uses: docker/build-push-action@v6
        with:
          context: weather-app/docker-final/statporter/
          push: true
          tags: burningstar4/statporter:latest
