---
name: CI - Format, Lint, and Test

"on":
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lint-format-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # ---- PYTHON ----
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python tools
        run: |
          pip install --upgrade pip
          pip install black flake8

      - name: Run Black (format check)
        run: black --check .

      - name: Run Flake8 (lint)
        run: flake8 weather-app/python

      # ---- FRONTEND/WEB ----
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Prettier
        run: npm install --global prettier

      - name: Run Prettier
        run: prettier --check "**/*.{js,json,css,html,md,yml,yaml}"

      # ---- DOCKER ----
      - name: Run Hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: "weather-app/docker/Dockerfile"

      # ---- YAML ----
      - name: Install yamllint
        run: sudo apt-get install -y yamllint

      - name: Run yamllint
        run: yamllint .
